# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'rock-template' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rock-template
  pod 'apps', :path => '../apps.podspec'
  pod 'FirebaseMessaging'
  pod 'FirebaseCore'

  target 'rock-templateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rock-templateUITests' do
    # Pods for testing
  end

end
